# User running EAP
user: "{{ ansible_user }}"

# Where EAP will be unzipped to
software_dir: /home/{{ user }}/software

# Zip file name for EAP
eap_zip: jboss-eap-7.2.0.zip

# Name of the dir created from unzipping eap_zip
eap_unzipped: jboss-eap-7.2

# Oracle JDK rpm name
oracle_rpm: jdk-8u201-linux-x64.rpm

# The interface EAP will run on
net_interface: enp0s8

# IP of net_interface
net_interface_ip: "{{ ansible_facts[net_interface].ipv4.address }}"

# path to oracle java
oracle_java_path: /usr/java/jdk1.8.0_201-amd64/jre/bin/java

# path to openjdk path
openjdk_java_path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre/bin/java