---
- name: Set to OpenJDK through alternatives
  command: alternatives --set java {{ openjdk_java_path }}

- name: Restart EAP 
  command: "{{ item }}"
  become: yes
  become_user: "{{ user }}"
  loop:
    - tmux kill-session -t javademo
    - tmux new -s javademo -d
    - tmux set-option -g allow-rename off
    - tmux rename-window -t javademo eap
    - tmux send -t javademo '{{ software_dir }}/{{ eap_unzipped }}/bin/standalone.sh -b {{ net_interface_ip }}' C-m

- name: Wait for EAP to start
  command: "{{ software_dir }}/{{ eap_unzipped }}/bin/jboss-cli.sh --connect --command=\"/interface=public:read-attribute(name=inet-address,resolve-expressions=true)\""
  register: result
  until: result.failed != true and result.stdout.find('success') != -1
  retries: 12
  delay: 5

- name: Redeploy HelloWorld
  command: "{{ item }}"
  become: yes
  become_user: vagrant
  loop:
    - tmux new-window 
    - tmux send -t javademo 'cd {{ software_dir }}/jboss-eap-quickstarts/helloworld' C-m
    - tmux rename-window -t javademo maven
    - tmux send -t javademo 'mvn clean package wildfly:deploy' C-m
      
- name: Finished!
  debug:
    msg: "http://{{ net_interface_ip }}:8080/helloworld"