---
- name: Set to OpenJDK through alternatives
  command: alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.201.b09-2.el7_6.x86_64/jre/bin/java

- name: Restart EAP 
  command: "{{ item }}"
  become: yes
  become_user: "{{ ansible_user }}"
  loop:
    - tmux kill-session -t javademo
    - tmux new -s javademo -d
    - tmux set-option -g allow-rename off
    - tmux rename-window -t javademo eap
    - tmux send -t javademo '/home/{{ ansible_user }}/software/jboss-eap-7.2/bin/standalone.sh -b {{ ansible_facts['enp0s8']['ipv4']['address'] }}' C-m

- name: Wait for EAP to start
  command: /home/vagrant/software/jboss-eap-7.2/bin/jboss-cli.sh --connect --command="/interface=public:read-attribute(name=inet-address,resolve-expressions=true)"
  register: result
  until: result.failed != true and result.stdout.find('success') != -1
  retries: 12
  delay: 5

- name: Redeploy HelloWorld
  command: "{{ item }}"
  become: yes
  become_user: vagrant
  loop:
    - tmux new-window -c /home/{{ ansible_user }}/software/jboss-eap-quickstarts/helloworld -t javademo
    - tmux rename-window -t javademo maven
    - tmux send -t javademo 'mvn clean package wildfly:deploy' C-m
    
- name: Finished!
  debug:
    msg: "http://{{ ansible_facts.enp0s8.ipv4.address }}:8080/helloworld"