---
- name: Copy EAP zip to host
  copy:
    src: files/{{ item }}
    dest: /tmp/{{ item }}
  loop:
    - "{{ eap_zip }}"


- name: Create EAP directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  loop:
    - "{{ software_dir }}" 
    
- name: Checkout modified HelloWorld quickstart
  git:
    repo: 'https://github.com/mmistretta/jboss-eap-quickstarts.git'
    dest: "{{ software_dir }}/jboss-eap-quickstarts"
  become: yes
  become_user: "{{ user }}"

- name: Add Maven repo
  yum_repository:
    name: maven
    description: Maven from Apache foundation
    baseurl: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-$releasever/$basearch/
    state: present
    gpgcheck: no
    enabled: yes

- name: Install maven unzip and tmux
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - tmux
    - apache-maven

- name: Unzip EAP
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ software_dir }}" 
    owner: "{{ user }}"
    remote_src: yes
  loop:
    - { name: 'jboss-eap', path: '/tmp/{{ eap_zip }}' }

