---
- name: Copy EAP and quickstart zips to host
  copy:
    src: files/{{ item }}
    dest: /tmp/{{ item }}
  loop:
    - jboss-eap-7.2.0.zip

- name: Create EAP directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - /home/{{ ansible_user }}/software/
    
- name: Checkout modified HelloWorld quickstart
  git:
    repo: 'https://github.com/mmistretta/jboss-eap-quickstarts.git'
    dest: /home/{{ ansible_user }}/software/jboss-eap-quickstarts
  become: yes
  become_user: "{{ ansible_user }}"

- name: Add Maven repo
  yum_repository:
    name: maven
    description: Maven from Apache foundation
    baseurl: http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-$releasever/$basearch/
    state: present
    gpgcheck: no
    enabled: yes

- name: Install Maven
  yum:
    name: apache-maven
    state: present

- name: Install unzip and tmux
  yum:
    name: "{{ item }}"
    state: latest
  loop:
    - unzip
    - tmux

- name: Unzip EAP
  unarchive:
    src: "{{ item.path }}"
    dest: /home/{{ ansible_user }}/software/
    owner: "{{ ansible_user }}"
    remote_src: yes
  loop:
    - { name: 'jboss-eap', path: '/tmp/jboss-eap-7.2.0.zip' }

